trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VAR_resource_group_name: 'myResourceGroup'
  TF_VAR_location: 'East US'

steps:
- task: UseTerraform@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'

- task: UseTerraform@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'

- task: UseTerraform@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
    args: '-auto-approve'
